service: read-with-you-ops

package:
  exclude:
    - src/**
    - webpack.config.js
    - node_modules/.cache/**
 
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: production
  region: cn-north-1
  endpointType: REGIONAL
    
functions:
  rwyweb:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /

resources:
  Resources:
    RwywebLambdaPermissionApiGateway:
      Properties:
        Principal: apigateway.amazonaws.com