service: read-with-you-ops

package:
  exclude:
    - webpack.config.js
    - node_modules/.cache/**
 
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: production
  region: cn-north-1
  endpointType: REGIONAL
    
functions:
  rwyweb:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /
  ddbhandler:
    handler: lambda.ddb_handler
    events:
      - stream: arn:aws-cn:dynamodb:cn-north-1:398835145439:table/Students_Registration/stream/2018-07-09T05:54:50.917
  course_notification_handler:
    handler: lambda.course_notification_handler
    events:
      - schedule:
          name: course-notification-job
          description: 'Job to detect and send course notification'
          rate: rate(2 hours)

resources:
  Resources:
    RwywebLambdaPermissionApiGateway:
      Properties:
        Principal: apigateway.amazonaws.com